# System configuration ========================================================= #
server:
  display-name: CRUD
  port: 8888

# Datasource & Thymeleaf configuration ================================================ #
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/yukidb
  thymeleaf:
    enabled: true
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
